/**
 * Renders `.tp/athlete.tp.md` — a fully-generated mirror of athlete settings
 * pulled from TrainingPeaks. Companion to the user-edited `ATHLETE.md` at the
 * workspace root.
 *
 * Every `tp pull` overwrites this file. Hand-edits will be lost.
 */
import path from "node:path";
import { writeAtomic } from "./fs.js";
import { TP_DIR } from "../config.js";
import type { TPAthleteSettings, TPZoneGroup, TPZoneBand } from "../api/types.js";
import type { LatestWeight } from "../api/athlete.js";

export interface AthleteTpInput {
  athleteId: number;
  generatedAt: Date;
  settings: TPAthleteSettings | null;
  latestWeight: LatestWeight | null;
}

/** Pick the zone group whose workoutTypeId matches `wid`, falling back to the first. */
function pickGroup(groups: TPZoneGroup[] | undefined, wid: number): TPZoneGroup | null {
  if (!groups || groups.length === 0) return null;
  return groups.find((g) => g.workoutTypeId === wid) ?? groups[0];
}

/** Convert m/s to seconds-per-km (run/general). */
function paceFromMps(mps: number): number {
  return 1000 / mps;
}

/** Convert m/s to seconds-per-100m (swim). */
function paceFrom100m(mps: number): number {
  return 100 / mps;
}

function fmtPace(totalSeconds: number): string {
  const m = Math.floor(totalSeconds / 60);
  const s = Math.round(totalSeconds - m * 60);
  return `${m}:${s.toString().padStart(2, "0")}`;
}

function renderZoneBands(bands: TPZoneBand[]): string {
  return bands
    .map((b) => `    - { label: ${jsonStr(b.label)}, min: ${b.minimum}, max: ${b.maximum} }`)
    .join("\n");
}

/** YAML-safe string. We keep it conservative: always JSON-quote. */
function jsonStr(s: string): string {
  return JSON.stringify(s);
}

export function renderAthleteTpMarkdown(input: AthleteTpInput): string {
  const { athleteId, generatedAt, settings, latestWeight } = input;

  if (!settings) {
    return [
      "---",
      "# Generated by `tp pull` from TrainingPeaks. Do not edit by hand.",
      `generated_at: ${generatedAt.toISOString()}`,
      `athlete_id: ${athleteId}`,
      "settings_available: false",
      "---",
      "",
      "# TrainingPeaks athlete settings",
      "",
      "TrainingPeaks did not return athlete settings (endpoint unavailable or empty).",
      "",
    ].join("\n");
  }

  const hrGeneral = pickGroup(settings.heartRateZones, 0);
  const hrBike = pickGroup(settings.heartRateZones, 2);
  const power = pickGroup(settings.powerZones, 0);
  const speedRun = pickGroup(settings.speedZones, 0);
  const speedSwim = pickGroup(settings.speedZones, 1);

  const ftp = power?.threshold ?? null;
  const lthr = hrGeneral?.threshold ?? null;
  const maxHr = hrGeneral?.maximumHeartRate ?? null;
  const restingHr = hrGeneral?.restingHeartRate ?? null;
  const lthrBike = hrBike?.threshold ?? null;
  const maxHrBike = hrBike?.maximumHeartRate ?? null;

  const runThresholdSecPerKm = speedRun ? Math.round(paceFromMps(speedRun.threshold)) : null;
  const swimCssSecPer100m = speedSwim ? Math.round(paceFrom100m(speedSwim.threshold)) : null;

  const lines: string[] = [];
  lines.push("---");
  lines.push("# Generated by `tp pull` from TrainingPeaks. Do not edit by hand.");
  lines.push("# Companion to ATHLETE.md (which holds your hand-edited current_block, goals, notes).");
  lines.push("");
  lines.push(`generated_at: ${generatedAt.toISOString()}`);
  lines.push(`athlete_id: ${athleteId}`);
  if (settings.timeZone) lines.push(`timezone: ${jsonStr(settings.timeZone)}`);
  if (settings.birthday) lines.push(`birthday: ${jsonStr(settings.birthday.slice(0, 10))}`);
  if (settings.gender) lines.push(`gender: ${jsonStr(settings.gender)}`);
  lines.push("");
  lines.push("# Thresholds");
  lines.push(`ftp_watts: ${ftp ?? "null"}`);
  lines.push(`lthr_bpm: ${lthr ?? "null"}`);
  lines.push(`max_hr: ${maxHr ?? "null"}`);
  lines.push(`resting_hr: ${restingHr ?? "null"}`);
  if (lthrBike !== null) lines.push(`lthr_bpm_bike: ${lthrBike}`);
  if (maxHrBike !== null) lines.push(`max_hr_bike: ${maxHrBike}`);
  if (runThresholdSecPerKm !== null) {
    lines.push(`threshold_pace_run_s_per_km: ${runThresholdSecPerKm}  # ${fmtPace(runThresholdSecPerKm)}/km`);
  }
  if (swimCssSecPer100m !== null) {
    lines.push(`swim_css_s_per_100m: ${swimCssSecPer100m}  # ${fmtPace(swimCssSecPer100m)}/100m`);
  }
  lines.push("");

  // Weight (latest from /metrics/v3).
  lines.push("# Body weight");
  if (latestWeight) {
    lines.push(`weight_kg: ${latestWeight.kg}`);
    lines.push(`weight_recorded: ${jsonStr(latestWeight.date)}`);
    if (latestWeight.source) lines.push(`weight_source: ${jsonStr(latestWeight.source)}`);
  } else {
    lines.push("weight_kg: null  # no weight metrics found");
  }
  lines.push("");

  // Zones.
  lines.push("zones:");
  if (power) {
    lines.push("  power:");
    lines.push(`    threshold: ${power.threshold}`);
    lines.push("    bands:");
    lines.push(renderZoneBands(power.zones));
  }
  if (hrGeneral) {
    lines.push("  hr:");
    lines.push(`    threshold: ${hrGeneral.threshold}`);
    lines.push("    bands:");
    lines.push(renderZoneBands(hrGeneral.zones));
  }
  if (hrBike) {
    lines.push("  hr_bike:");
    lines.push(`    threshold: ${hrBike.threshold}`);
    lines.push("    bands:");
    lines.push(renderZoneBands(hrBike.zones));
  }
  if (speedRun) {
    lines.push("  pace_run:");
    lines.push(`    threshold_mps: ${speedRun.threshold}`);
    lines.push(`    threshold_s_per_km: ${runThresholdSecPerKm ?? "null"}`);
    lines.push("    bands_mps:");
    lines.push(renderZoneBands(speedRun.zones));
  }
  if (speedSwim) {
    lines.push("  pace_swim:");
    lines.push(`    threshold_mps: ${speedSwim.threshold}`);
    lines.push(`    threshold_s_per_100m: ${swimCssSecPer100m ?? "null"}`);
    lines.push("    bands_mps:");
    lines.push(renderZoneBands(speedSwim.zones));
  }
  lines.push("---");
  lines.push("");
  lines.push("# TrainingPeaks athlete settings (auto-synced)");
  lines.push("");
  lines.push("This file mirrors the FTP, threshold HR, max HR, weight, and zones");
  lines.push("currently configured in TrainingPeaks. It is regenerated on every");
  lines.push("`tp pull`. For block notes, goals, and free-form context, edit");
  lines.push("`ATHLETE.md` (at the workspace root) instead.");
  lines.push("");
  return lines.join("\n");
}

export async function writeAthleteTpFile(outDir: string, input: AthleteTpInput): Promise<string> {
  const p = path.join(outDir, TP_DIR, "athlete.tp.md");
  const md = renderAthleteTpMarkdown(input);
  await writeAtomic(p, md);
  return p;
}
