/**
 * Renders `.tp/events.md` — auto-synced TrainingPeaks events/races for a window.
 *
 * Companion to `.tp/athlete.tp.md`. Regenerated every `tp pull`. Hand-edits lost.
 */
import path from "node:path";
import { writeAtomic } from "./fs.js";
import { TP_DIR } from "../config.js";
import type { Event } from "../transform/workout.js";

export interface EventsFileInput {
  athleteId: number;
  generatedAt: Date;
  /** IANA timezone — used only to compute "today" for the upcoming/past split. */
  timezone: string;
  /** Window over which events were fetched. */
  range: { from: Date; to: Date };
  events: Event[];
}

function todayInTz(now: Date, tz: string): string {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: tz,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(now);
}

function diffDays(fromYmd: string, toYmd: string): number {
  const a = new Date(`${fromYmd}T00:00:00Z`).getTime();
  const b = new Date(`${toYmd}T00:00:00Z`).getTime();
  return Math.round((b - a) / 86400000);
}

function renderEventLine(e: Event, today: string | null): string {
  const tail: string[] = [];
  if (e.priority) tail.push(`[${e.priority}]`);
  if (e.sport) tail.push(e.sport);
  if (typeof e.ctlTarget === "number") tail.push(`CTL target ${e.ctlTarget}`);
  const meta = tail.length > 0 ? ` · ${tail.join(" · ")}` : "";
  if (today && e.date >= today) {
    const days = diffDays(today, e.date);
    return `- **${e.date}** (T-${days}d) — ${e.title}${meta}`;
  }
  return `- **${e.date}** — ${e.title}${meta}`;
}

export function renderEventsMarkdown(input: EventsFileInput): string {
  const today = todayInTz(input.generatedAt, input.timezone);

  // De-dupe by id (some events can recur across chunked event fetches).
  const seen = new Set<string>();
  const dedup: Event[] = [];
  for (const e of input.events) {
    const k = `${e.id ?? "?"}|${e.date}|${e.title}`;
    if (seen.has(k)) continue;
    seen.add(k);
    dedup.push(e);
  }

  const upcoming = dedup
    .filter((e) => e.date >= today)
    .sort((a, b) => a.date.localeCompare(b.date) || a.title.localeCompare(b.title));
  const past = dedup
    .filter((e) => e.date < today)
    .sort((a, b) => b.date.localeCompare(a.date) || a.title.localeCompare(b.title));

  const fromStr = input.range.from.toISOString().slice(0, 10);
  const toStr = input.range.to.toISOString().slice(0, 10);

  const lines: string[] = [];
  lines.push("---");
  lines.push("# Generated by `tp pull` from TrainingPeaks. Do not edit by hand.");
  lines.push(`generated_at: ${input.generatedAt.toISOString()}`);
  lines.push(`athlete_id: ${input.athleteId}`);
  lines.push(`timezone: "${input.timezone}"`);
  lines.push("window:");
  lines.push(`  from: ${fromStr}`);
  lines.push(`  to:   ${toStr}`);
  lines.push("counts:");
  lines.push(`  upcoming: ${upcoming.length}`);
  lines.push(`  past: ${past.length}`);
  lines.push(`  total: ${dedup.length}`);
  lines.push("---");
  lines.push("");
  lines.push("# TrainingPeaks events (auto-synced)");
  lines.push("");

  lines.push("## Upcoming");
  lines.push("");
  if (upcoming.length === 0) {
    lines.push("_No upcoming events._");
    lines.push("");
  } else {
    for (const e of upcoming) {
      lines.push(renderEventLine(e, today));
      if (e.description) {
        lines.push("");
        lines.push(blockquote(e.description));
        lines.push("");
      }
    }
    lines.push("");
  }

  lines.push("## Past");
  lines.push("");
  if (past.length === 0) {
    lines.push("_No past events in window._");
    lines.push("");
  } else {
    for (const e of past) {
      lines.push(renderEventLine(e, null));
      if (e.description) {
        lines.push("");
        lines.push(blockquote(e.description));
        lines.push("");
      }
    }
    lines.push("");
  }

  return lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd() + "\n";
}

function blockquote(text: string): string {
  return text
    .split(/\r?\n/)
    .map((line) => (line.length === 0 ? ">" : `> ${line}`))
    .join("\n");
}

export async function writeEventsFile(outDir: string, input: EventsFileInput): Promise<string> {
  const p = path.join(outDir, TP_DIR, "events.md");
  await writeAtomic(p, renderEventsMarkdown(input));
  return p;
}
